import { Template, SurveyField, DEFAULT_SETTINGS } from './types'

// Built-in templates with real question content
export const SEED_TEMPLATES: Omit<Template, 'created_at'>[] = [
  {
    id: 'tpl-mbti-lite',
    title: 'MBTI 性格速测',
    description: '12 道题快速测出你的 MBTI 倾向，每个维度 3 题',
    category: 'personality',
    cover_image: null,
    tags: ['性格', 'MBTI', '心理'],
    is_featured: true,
    use_count: 128,
    fields: [
      // E/I 维度 (3 题)
      { id: 'ei1', type: 'radio', label: '参加一场有很多陌生人的派对，你的第一反应是？', required: true, options: ['兴奋，可以认识新朋友', '有点紧张，但会努力融入', '想找个借口不去'], description: '外向(E) vs 内向(I)' },
      { id: 'ei2', type: 'radio', label: '忙碌一天后，你更想怎么恢复精力？', required: true, options: ['约朋友出来吃饭聊天', '一个人待着看剧或发呆', '看心情，但大部分时候想独处'] },
      { id: 'ei3', type: 'radio', label: '工作/学习中遇到难题时，你倾向于？', required: true, options: ['找人讨论，边说边想', '自己先想清楚再找人确认', '一定要自己想通才安心'] },
      // S/N 维度 (3 题)
      { id: 'sn1', type: 'radio', label: '朋友描述一个新产品时，你更在意？', required: true, options: ['它具体能做什么、怎么用', '它背后的理念和未来潜力'], description: '实感(S) vs 直觉(N)' },
      { id: 'sn2', type: 'radio', label: '看一部电影时，你更关注？', required: true, options: ['剧情细节和画面是否合理', '隐喻象征和深层主题'] },
      { id: 'sn3', type: 'radio', label: '规划下个月的安排时，你通常？', required: true, options: ['基于过去经验，安排确定能做的事', '想尝试没做过的新事物，细节之后再说'] },
      // T/F 维度 (3 题)
      { id: 'tf1', type: 'radio', label: '好朋友做了一个你觉得不太好的决定，你会？', required: true, options: ['直接指出问题所在', '先关心他的感受，再委婉提建议'], description: '思维(T) vs 情感(F)' },
      { id: 'tf2', type: 'radio', label: '团队中产生分歧时，你更倾向于？', required: true, options: ['分析哪个方案效率最高', '考虑哪个方案让大家都舒服'] },
      { id: 'tf3', type: 'radio', label: '评价一件事情时，你更看重？', required: true, options: ['是否公平、有道理', '当事人的感受和处境'] },
      // J/P 维度 (3 题)
      { id: 'jp1', type: 'radio', label: '旅行前一天你通常？', required: true, options: ['行李早就收好了，行程也确认过', '大致想了想，明天出发前再收拾'], description: '判断(J) vs 感知(P)' },
      { id: 'jp2', type: 'radio', label: '你的待办清单/日程表使用情况？', required: true, options: ['认真记录并按时完成，划掉很爽', '偶尔记但经常不看，靠感觉来'] },
      { id: 'jp3', type: 'radio', label: '面对一个 deadline，你的节奏是？', required: true, options: ['提前完成，留出余量', '截止日期就是最好的动力'] },
    ] as SurveyField[],
    settings: {
      ...DEFAULT_SETTINGS,
      displayMode: 'step',
      theme: {
        primaryColor: '#8b5cf6',
        backgroundColor: '#ffffff',
        fontFamily: 'default',
        thankYouMessage: '测试完成！根据你的选择倾向，可以对照 MBTI 四个维度看看自己偏向哪个类型~',
        backgroundGradient: 'linear-gradient(135deg, #f5f3ff 0%, #ede9fe 100%)',
      },
    },
  },
  {
    id: 'tpl-love-language',
    title: '你的爱情语言是什么？',
    description: '基于 Gary Chapman 五种爱的语言理论，测测你最看重哪种爱的表达',
    category: 'social',
    cover_image: null,
    tags: ['恋爱', '情感', '心理'],
    is_featured: true,
    use_count: 96,
    fields: [
      { id: 'q1', type: 'radio', label: '在恋爱中，哪种行为最让你感到被爱？', required: true, options: ['对方真诚地说"你对我很重要"', '收到对方用心准备的小礼物', '对方专门空出一整天只陪你', '对方主动帮你处理麻烦事', '对方从背后拥抱你'], description: '肯定言辞/礼物/优质时间/服务行为/身体接触' },
      { id: 'q2', type: 'radio', label: '你和伴侣吵架后，最能让你消气的是？', required: true, options: ['对方诚恳地说出你的好', '对方买了你一直想要的东西', '对方放下一切安静地陪着你', '对方二话不说把家务全做了', '对方轻轻握住你的手'] },
      { id: 'q3', type: 'radio', label: '以下哪种日常最让你心动？', required: true, options: ['对方在朋友面前称赞你', '包里发现对方偷偷塞的小零食', '两人一起做饭，聊着当天的事', '发现对方已经把车加满了油', '看电视时对方自然地把你搂进怀里'] },
      { id: 'q4', type: 'radio', label: '如果只能选一种周年纪念方式？', required: true, options: ['收到一封手写的长信', '交换彼此精心挑选的礼物', '两人去一个新的地方旅行', '对方为你手作一顿烛光晚餐', '在家什么都不做，只是拥在一起'] },
      { id: 'q5', type: 'radio', label: '异地恋中你最无法忍受的是？', required: true, options: ['对方很少主动表达想你', '重要日子收不到任何东西', '找不到共同做一件事的方式', '遇到困难时对方无法帮忙', '很长时间无法有肢体接触'] },
      { id: 'q6', type: 'radio', label: '你最容易被哪种相处方式感动？', required: true, options: ['对方记得你无意中说过的话', '对方攒了很久给你一个惊喜', '对方推掉所有安排只为陪你', '你加班时对方默默送来夜宵', '对方不管在哪都自然地牵你的手'] },
      { id: 'q7', type: 'radio', label: '你表达爱的方式更接近？', required: true, options: ['经常夸对方、说鼓励的话', '用心准备节日礼物和惊喜', '安排高质量的两人时间', '默默为对方做很多事', '喜欢亲吻、拥抱、肢体亲近'] },
      { id: 'q8', type: 'radio', label: '恋爱中最让你受伤的是？', required: true, options: ['对方说了否定你的话', '对方忘了重要日子', '对方总说忙没时间陪你', '你忙得焦头烂额对方无动于衷', '对方回避你的肢体亲近'] },
    ] as SurveyField[],
    settings: {
      ...DEFAULT_SETTINGS,
      displayMode: 'step',
      theme: {
        primaryColor: '#ec4899',
        backgroundColor: '#ffffff',
        fontFamily: 'default',
        thankYouMessage: '你选择最多的选项对应的就是你的主要爱的语言。把结果分享给另一半，让 TA 知道怎样爱你才最到位~',
        backgroundGradient: 'linear-gradient(135deg, #fdf2f8 0%, #fce7f3 100%)',
      },
    },
  },
  {
    id: 'tpl-friend-quiz',
    title: '你有多了解我？（好友默契测试）',
    description: '把正确答案改成你自己的，发给朋友来测试默契度！',
    category: 'social',
    cover_image: null,
    tags: ['社交', '好友', '互动'],
    is_featured: true,
    use_count: 214,
    fields: [
      { id: 'q1', type: 'radio', label: '我最喜欢的颜色是？', required: true, options: ['蓝色', '粉色', '绿色', '黑色', '白色'], description: '💡 使用前把选项改成你自己的答案' },
      { id: 'q2', type: 'radio', label: '以下哪个最能让我崩溃？', required: true, options: ['手机没电', '外卖送错', '等人迟到', '计划被打乱', '被人误解'] },
      { id: 'q3', type: 'radio', label: '深夜emo时我会做什么？', required: true, options: ['听歌', '刷短视频', '找人聊天', '独自发呆', '疯狂吃东西'] },
      { id: 'q4', type: 'radio', label: '如果我突然有了一百万，我第一件事会？', required: true, options: ['先存起来', '买房/车', '辞职旅行', '请朋友吃饭', '投资理财'] },
      { id: 'q5', type: 'radio', label: '我最受不了哪种人？', required: true, options: ['说话不算数的', '过于自我中心的', '优柔寡断的', '太八卦的', '不守时的'] },
      { id: 'q6', type: 'radio', label: '我点外卖时通常选？', required: true, options: ['收藏夹里的老几样', '看销量排名选', '心情来了随便点', '被图片吸引的新店', '朋友推荐的'] },
      { id: 'q7', type: 'radio', label: '我的手机屏幕使用时间最多花在？', required: true, options: ['微信/QQ聊天', '短视频', '小红书/微博', '游戏', '追剧/看书'] },
      { id: 'q8', type: 'radio', label: '我理想的退休生活是？', required: true, options: ['开一家小店', '环游世界', '回乡下种地', '每天睡到自然醒', '做自媒体/写书'] },
      { id: 'q9', type: 'text', label: '你觉得我最大的优点是什么？', required: true, placeholder: '认真写哦~' },
      { id: 'q10', type: 'text', label: '用一首歌/一句歌词形容我', required: false, placeholder: '随便什么都行' },
    ] as SurveyField[],
    settings: {
      ...DEFAULT_SETTINGS,
      displayMode: 'step',
      theme: {
        primaryColor: '#f59e0b',
        backgroundColor: '#ffffff',
        fontFamily: 'rounded',
        thankYouMessage: '答完啦！把你的答案截图发给我，看看你能得多少分~',
        backgroundGradient: 'linear-gradient(135deg, #fef3c7 0%, #fde68a 100%)',
      },
    },
  },
  {
    id: 'tpl-stress-test',
    title: '你的压力指数有多高？',
    description: '参考 PSS 压力感知量表设计，8 道题评估近两周压力水平',
    category: 'personality',
    cover_image: null,
    tags: ['心理', '压力', '健康'],
    is_featured: false,
    use_count: 67,
    fields: [
      { id: 'q1', type: 'radio', label: '过去两周，你多久感到无法控制生活中的重要事情？', required: true, options: ['从不', '偶尔', '有时', '经常', '总是'], optionScores: { '从不': 0, '偶尔': 1, '有时': 2, '经常': 3, '总是': 4 } },
      { id: 'q2', type: 'radio', label: '过去两周，你多久感到事情堆积如山，无法应付？', required: true, options: ['从不', '偶尔', '有时', '经常', '总是'], optionScores: { '从不': 0, '偶尔': 1, '有时': 2, '经常': 3, '总是': 4 } },
      { id: 'q3', type: 'radio', label: '过去两周，你多久因为意料之外的事情而心烦意乱？', required: true, options: ['从不', '偶尔', '有时', '经常', '总是'], optionScores: { '从不': 0, '偶尔': 1, '有时': 2, '经常': 3, '总是': 4 } },
      { id: 'q4', type: 'radio', label: '过去两周，你多久感到紧张和焦虑？', required: true, options: ['从不', '偶尔', '有时', '经常', '总是'], optionScores: { '从不': 0, '偶尔': 1, '有时': 2, '经常': 3, '总是': 4 } },
      { id: 'q5', type: 'radio', label: '过去两周，你多久感到自己能有效地处理问题？', required: true, options: ['总是', '经常', '有时', '偶尔', '从不'], optionScores: { '总是': 0, '经常': 1, '有时': 2, '偶尔': 3, '从不': 4 }, description: '（反向计分题）' },
      { id: 'q6', type: 'radio', label: '过去两周，你多久感到事情在朝好的方向发展？', required: true, options: ['总是', '经常', '有时', '偶尔', '从不'], optionScores: { '总是': 0, '经常': 1, '有时': 2, '偶尔': 3, '从不': 4 }, description: '（反向计分题）' },
      { id: 'q7', type: 'radio', label: '过去两周，你的睡眠质量如何？', required: true, options: ['很好', '还行', '一般', '较差', '很差'], optionScores: { '很好': 0, '还行': 1, '一般': 2, '较差': 3, '很差': 4 } },
      { id: 'q8', type: 'radio', label: '过去两周，你多久感到自己精力不足？', required: true, options: ['从不', '偶尔', '有时', '经常', '总是'], optionScores: { '从不': 0, '偶尔': 1, '有时': 2, '经常': 3, '总是': 4 } },
    ] as SurveyField[],
    settings: {
      ...DEFAULT_SETTINGS,
      displayMode: 'step',
      scoringMode: true,
      scoreRanges: [
        { min: 0, max: 8, label: '压力较低 🟢', description: '你目前的压力处于正常范围，状态不错，继续保持健康的生活节奏。' },
        { min: 9, max: 16, label: '压力中等 🟡', description: '你感受到一定的压力，建议适当运动、保证睡眠，找到适合自己的放松方式。' },
        { min: 17, max: 24, label: '压力较高 🟠', description: '你近期承受的压力较大，建议减少不必要的任务，和信任的人聊聊，给自己放个假。' },
        { min: 25, max: 32, label: '压力过载 🔴', description: '你正在经历很大的心理压力。请重视自己的身心健康，必要时寻求专业心理咨询帮助。' },
      ],
      theme: {
        primaryColor: '#06b6d4',
        backgroundColor: '#ffffff',
        fontFamily: 'default',
        thankYouMessage: '⚠️ 本测试仅供参考，不构成专业诊断。如持续感到不适，请寻求专业帮助。',
        backgroundGradient: 'linear-gradient(135deg, #ecfeff 0%, #cffafe 100%)',
      },
    },
  },
  {
    id: 'tpl-travel-style',
    title: '你是哪种旅行人格？',
    description: '7 道题解锁你的旅行 DNA，下次出行参考一下',
    category: 'fun',
    cover_image: null,
    tags: ['旅行', '生活', '趣味'],
    is_featured: false,
    use_count: 45,
    fields: [
      { id: 'q1', type: 'radio', label: '到了一个完全陌生的城市，你第一件事做什么？', required: true, options: ['找一家当地评分最高的餐厅', '去标志性景点打卡拍照', '漫无目的地走街串巷', '先回酒店休息再说', '打开地图研究路线'] },
      { id: 'q2', type: 'radio', label: '你的行李箱里最多的是？', required: true, options: ['各种搭配好的衣服（拍照要好看）', '实用装备（充电宝、转换插头、药品）', '零食和泡面（省钱必备）', '几乎空箱（留空间买东西带回来）', '相机镜头各种设备'] },
      { id: 'q3', type: 'radio', label: '关于旅途中的吃饭，你的态度是？', required: true, options: ['提前做功课，必须吃到当地最地道的', '路过什么吃什么，体验大于味道', '能省就省，把钱花在体验上', '吃好很重要，旅行就是要犒劳自己', '跟着同行人走，别人吃什么我吃什么'] },
      { id: 'q4', type: 'radio', label: '同行伙伴临时想改计划，你的反应？', required: true, options: ['内心有点不爽但会配合', '无所谓，本来就没啥计划', '看改成什么，分析一下合不合理', '开心，说不定会有意外收获', '提出折中方案，两边都照顾到'] },
      { id: 'q5', type: 'radio', label: '旅行中你的拍照风格？', required: true, options: ['精心构图，每张都要修图发朋友圈', '随手拍记录，重在当下感受', '几乎不拍照，用眼睛记住就好', '主要拍吃的和风景，很少自拍', '疯狂拍，回来再慢慢选'] },
      { id: 'q6', type: 'radio', label: '最让你心动的旅行方式是？', required: true, options: ['一个人背包说走就走', '和最好的朋友自驾', '精心规划的蜜月旅行', '跟一个靠谱的旅行团', '当地 long stay，像本地人一样生活'] },
      { id: 'q7', type: 'radio', label: '旅行结束最后一天你通常？', required: true, options: ['依依不舍，已经在想下次来', '松一口气，终于可以回家了', '疯狂采购伴手礼', '抓紧最后时间再逛一个景点', '整理照片发一条旅行总结'] },
    ] as SurveyField[],
    settings: {
      ...DEFAULT_SETTINGS,
      displayMode: 'step',
      theme: {
        primaryColor: '#059669',
        backgroundColor: '#ffffff',
        fontFamily: 'default',
        thankYouMessage: '你的旅行人格已解锁！把结果分享给旅伴看看你们适不适合一起出行~',
        backgroundGradient: 'linear-gradient(135deg, #ecfdf5 0%, #d1fae5 100%)',
      },
    },
  },
  {
    id: 'tpl-satisfaction',
    title: '客户满意度调查',
    description: '标准 NPS + 满意度 + 开放反馈的调查模板，可直接修改使用',
    category: 'utility',
    cover_image: null,
    tags: ['满意度', '反馈', '商业'],
    is_featured: false,
    use_count: 83,
    fields: [
      { id: 'q1', type: 'radio', label: '您使用我们的产品/服务多长时间了？', required: true, options: ['不到1个月', '1-6个月', '6个月-1年', '1年以上'] },
      { id: 'q2', type: 'radio', label: '您是通过什么渠道了解我们的？', required: true, options: ['朋友/同事推荐', '社交媒体（小红书/抖音等）', '搜索引擎', '线下活动或广告', '其他'] },
      { id: 'q3', type: 'rating', label: '您对产品/服务的整体满意度打几分？', required: true, maxRating: 5 },
      { id: 'q4', type: 'nps', label: '您有多大可能向朋友或同事推荐我们？（0=绝不，10=一定会）', required: true, npsLeftLabel: '绝对不会', npsRightLabel: '一定推荐' },
      { id: 'q5', type: 'checkbox', label: '您最满意的方面有哪些？（可多选）', required: false, options: ['产品功能', '使用体验', '客服响应', '性价比', '更新迭代速度'] },
      { id: 'q6', type: 'checkbox', label: '您觉得最需要改进的是？（可多选）', required: false, options: ['功能还不够完善', '使用上有些复杂', '客服不够及时', '价格偏高', '缺少某些我需要的功能'] },
      { id: 'q7', type: 'text', label: '如果可以改进一个地方，您最希望是？', required: false, multiline: true, placeholder: '您的建议对我们非常重要' },
    ] as SurveyField[],
    settings: {
      ...DEFAULT_SETTINGS,
      displayMode: 'page',
      theme: {
        primaryColor: '#4F46E5',
        backgroundColor: '#ffffff',
        fontFamily: 'default',
        thankYouMessage: '感谢您的反馈！您的每一条建议都会帮助我们做得更好。',
        backgroundGradient: 'linear-gradient(135deg, #f0ebf8 0%, #e8e0f0 100%)',
      },
    },
  },
]
